apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-nginx"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Values.secret_name }}
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service_name }}
                port:
                  number: 80
  


