apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.appname }}
  ports:
  - protocol: {{ .Values.protocol }}
    port: 80
    targetPort: 8080
  type: {{ .Values.type }}

