appname: my-app
replicacount: 2
containername: gatusapp
namespace: app-space
image:
  name: 038774803581.dkr.ecr.eu-west-2.amazonaws.com/gatusapp
  tag: latest
domain: mubashir.site
service_name: service-gatus-app
secret_name: mubashir-site-tls
protocol: TCP
type: ClusterIP

{{ .Values.type }}
{{ .Values.protocol }}
{{ .Values.secret_name }}
{{ .Values.service_name }}
{{ .Values.domain }}
{{ .Values.replicacount }}
{{ .Values.containername }}
{{ .Values.namespace }}
{{ .Values.image.name }}
{{ .Values.image.tag }}
